### ISSUE TITLE
Ability to output to file

### ISSUE THREAD

**Issue by natotthomer** [jeffjewiss/postcss-stats-reporter#129]
I would love to be able to include an option that provides some way to save the output to a file.

**Comment by jeffjewiss** [comment]
That should be possible by passing options into the reporter and writing to a file instead of logging.

What's the use case for this? Would it be useful to have the output as json or a csv?

Any chance you could submit a PR?

Thanks!

**Comment by natotthomer** [comment]
The use case is that our organization wants to be able to track stats over
time so we can better analyze the size and complexity of PRs and builds.
JSON would be helpful, but even a .txt file or log file would suffice, to
be honest. I can try to submit a PR, I’m a bit busy at the moment. Thanks
for the speedy response!
